apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: infnet-app
spec:
  selector:
    app: app-course
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer